# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhOBRxUyrYio5pMQseHFXqP5zSBQv-8F
"""

import requests

url = "https://api.fda.gov/device/event.json"
params = {
    "search": 'device.manufacturer_d_name:"GE HEALTHCARE"',
    "limit": 5
}

response = requests.get(url, params=params)
print("Status code:", response.status_code)
print("Full URL called:", response.url)
print("Raw response:")
print(response.text[:1000])

import requests
import pandas as pd

url = "https://api.fda.gov/device/event.json"
params = {
    "search": 'device.manufacturer_d_name:"GE HEALTHCARE"',
    "limit": 1000,
    "api_key": "7gJ3Jc4J0f0Ng8GcjT0b7NRbqdnCgCdysxF7CBAy"
}

response = requests.get(url, params=params)
print(response.status_code)

data = response.json()["results"]
df = pd.json_normalize(data)
df.to_csv("ge_healthcare_device_events.csv", index=False)

print(f"Saved {len(df)} records to ge_healthcare_device_events.csv")

import pandas as pd

df = pd.read_csv('ge_healthcare_device_events.csv')


threshold = 0.6
null_percent = df.isnull().mean()
cols_to_drop = null_percent[null_percent > threshold].index
df_cleaned = df.drop(columns=cols_to_drop , inplace=False)

# print(f"Dropped {len(cols_to_drop)} columns, {df_cleaned.shape[1]} columns bache")
df_cleaned.to_csv('ge_cleaned.csv', index=False)

df_cleaned=pd.read_csv('ge_cleaned.csv')
df_cleaned.shape

df.head(5)

print(len(df.columns))
print(df.columns.tolist())

print(df_cleaned.isnull().sum())

df_cleaned = df_cleaned.drop(columns=['pma_pmn_number', 'reprocessed_and_reused_flag', 'date_manufacturer_received', 'product_problems','reporter_state_code'])

df_cleaned['date_of_event'] = df_cleaned['date_of_event'].fillna(df_cleaned['date_received'])

# df_cleaned = df_cleaned.drop(columns=['mfr_report_type'])
df_cleaned = df_cleaned.drop(columns=['reporter_country_code', 'reporter_occupation_code'])

df_cleaned.shape

df_cleaned = df_cleaned.dropna(subset=['event_type', 'product_problem_flag', 'date_added', 'date_report', 'adverse_event_flag'])
print(df_cleaned.shape)

import ast

df_cleaned['device_name'] = df_cleaned['device'].apply(lambda x: ast.literal_eval(x)[0]['generic_name'] if isinstance(x, str) else None)
df_cleaned['device_brand'] = df_cleaned['device'].apply(lambda x: ast.literal_eval(x)[0]['brand_name'] if isinstance(x, str) else None)
df_cleaned['patient_age'] = df_cleaned['patient'].apply(lambda x: ast.literal_eval(x)[0]['patient_age'] if isinstance(x, str) else None)
df_cleaned['event_description'] = df_cleaned['mdr_text'].apply(lambda x: ast.literal_eval(x)[0]['text'] if isinstance(x, str) else None)

df_cleaned = df_cleaned.drop(columns=['device', 'patient', 'mdr_text'])

print(df_cleaned.shape)
print(df_cleaned.head())

df_cleaned.to_csv('ge_final_clean.csv', index=False)

print(df_cleaned.shape)
print(df_cleaned.columns.tolist())
print(df_cleaned.head(3))

import pandas as pd

df = pd.read_csv('ge_final_clean.csv')
print(df.shape)
print(df.tail())  # check karo end mein koi blank row toh nahi

df.to_csv('ge_final_clean_v2.csv', index=False, quoting=1)

df['event_description'] = df['event_description'].str.replace('\n', ' ', regex=False).str.replace('\r', ' ', regex=False)

df.to_csv('ge_final_clean_v3.csv', index=False, quoting=1)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_final = pd.read_csv('ge_final_clean_v3.csv')
print(df_final.shape)
print(df_final.columns.tolist())

df_final['date_received'] = df_final['date_received'].astype(str).str.extract(r'(\d{8})$')
df_final['date_received'] = pd.to_datetime(df_final['date_received'], format='%Y%m%d', errors='coerce')
df_final['year'] = df_final['date_received'].dt.year

print(df_final['year'].value_counts().sort_index())

plt.figure(figsize=(8,5))
sns.countplot(data=df_final, x='event_type', order=df_final['event_type'].value_counts().index)
plt.title('Event Type Distribution')
plt.show()


top_devices = df_final['device_name'].value_counts().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=top_devices.values, y=top_devices.index)
plt.title('Top 10 Devices by Event Count')
plt.show()

severe = df_final[df_final['event_type'].isin(['Death', 'Injury'])]
severe_counts = severe['device_name'].value_counts().head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=severe_counts.values, y=severe_counts.index, palette='Reds_r')
plt.title('Top 10 Devices by Severe Events (Death/Injury)')
plt.xlabel('Count')
plt.show()



yearly = df_final['year'].value_counts().sort_index()

plt.figure(figsize=(10,6))
plt.plot(yearly.index, yearly.values, marker='o')
plt.title('Events Over Time')
plt.xlabel('Year')
plt.ylabel('Number of Events')
plt.grid(True)
plt.show()


print(df_final['date_received'].head())
print(df_final['year'].value_counts())

top10 = df_final['device_name'].value_counts().head(10).index
subset = df_final[df_final['device_name'].isin(top10)]

pivot = pd.crosstab(subset['device_name'], subset['event_type'])
pivot.plot(kind='barh', stacked=True, figsize=(10,7), colormap='tab10')
plt.title('Event Type Breakdown by Top 10 Devices')
plt.xlabel('Count')
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(pivot, annot=True, fmt='d', cmap='YlOrRd')
plt.title('Device vs Event Type Heatmap')
plt.show()

from sklearn.feature_extraction.text import CountVectorizer


descriptions = df_final['event_description'].dropna().astype(str)

vectorizer = CountVectorizer(stop_words='english', max_features=20)
word_counts = vectorizer.fit_transform(descriptions)

words = vectorizer.get_feature_names_out()
counts = word_counts.sum(axis=0).A1

word_freq = pd.DataFrame({'word': words, 'count': counts}).sort_values('count', ascending=False)
print(word_freq)

plt.figure(figsize=(10,6))
sns.barplot(data=word_freq, x='count', y='word')
plt.title('Top 20 Keywords in Event Descriptions')
plt.show()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import text

custom_stopwords = list(text.ENGLISH_STOP_WORDS.union([
    'reported', 'device', 'patient', 'stated', 'noted', 'said', 'reports',
    'did', 'note', 'ge', 'healthcare', 'pt', 'follow', 'followup', 'issued',
    'completed', 'ongoing', 'occurrence', 'investigation', 'event', 'events',
    'customer', 'time', 'issue', 'monitor', 'probe'
]))
# descriptions = df_final['event_description'].dropna().astype(str)

# vectorizer = CountVectorizer(stop_words=custom_stopwords, max_features=20)
# word_counts = vectorizer.fit_transform(descriptions)

# words = vectorizer.get_feature_names_out()
# counts = word_counts.sum(axis=0).A1

# word_freq = pd.DataFrame({'word': words, 'count': counts}).sort_values('count', ascending=False)
# print(word_freq)

# plt.figure(figsize=(10,6))
# sns.barplot(data=word_freq, x='count', y='word')
# plt.title('Top 20 Keywords in Event Descriptions (Filtered)')
# plt.show()

from sklearn.model_selection import train_test_split

df_model = df_final.dropna(subset=['event_description', 'device_name', 'event_type']).copy()

X = df_model[['device_name', 'event_description']]
y = df_model['event_type']

print(X.shape, y.shape)
print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

preprocessor = ColumnTransformer(
    transformers=[
        ('device_ohe', OneHotEncoder(handle_unknown='ignore'), ['device_name']),
        ('desc_tfidf', TfidfVectorizer(stop_words='english', max_features=100), 'event_description')
    ]
)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, n_estimators=120))
])

model_pipeline.fit(X_train, y_train)

y_pred = model_pipeline.predict(X_test)

from sklearn.metrics import precision_score, f1_score, accuracy_score

y_pred_rf = model_pipeline.predict(X_test)

print("Random Forest:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision (weighted):", precision_score(y_test, y_pred_rf, average='weighted'))
print("F1-score (weighted):", f1_score(y_test, y_pred_rf, average='weighted'))

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

model_pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=42, n_estimators=175))
])

model_pipeline_xgb.fit(X_train, y_train_encoded)
y_pred_xgb = model_pipeline_xgb.predict(X_test)

print("XGBoost:")
print("Accuracy:", accuracy_score(y_test_encoded, y_pred_xgb))
print("Precision (weighted):", precision_score(y_test_encoded, y_pred_xgb, average='weighted'))
print("F1-score (weighted):", f1_score(y_test_encoded, y_pred_xgb, average='weighted'))

df_model['severity'] = df_model['event_type'].apply(
    lambda x: 'Severe' if x in ['Death','Injury'] else 'Non-Severe'
)

X = df_model[['device_name', 'event_description']]
y = df_model['severity']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model_pipeline_binary = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, n_estimators=125, class_weight='balanced'))
])

model_pipeline_binary.fit(X_train, y_train)
y_pred_binary = model_pipeline_binary.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_binary))
print("Precision (weighted):", precision_score(y_test, y_pred_binary, average='weighted'))
print("F1-score (weighted):", f1_score(y_test, y_pred_binary, average='weighted'))

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

# --- Recreate the ORIGINAL 4-class train/test split ---
# (X_train/y_train currently hold the binary Severe/Non-Severe data from the
# previous cell, so we must rebuild the 4-class split before retraining)
X = df_model[['device_name', 'event_description']]
y = df_model['event_type']   # 4-class target: Malfunction / Injury / Death / Other

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# --- Redefine a FRESH preprocessor (not shared with the binary pipeline) ---
# Using every unique device name from the full dataset so OneHotEncoder
# categories are consistent and complete
all_device_names = X['device_name'].unique().tolist()

preprocessor_fixed = ColumnTransformer(
    transformers=[
        ('device_ohe', OneHotEncoder(handle_unknown='ignore', categories=[sorted(all_device_names)]), ['device_name']),
        ('desc_tfidf', TfidfVectorizer(stop_words='english', max_features=100), 'event_description')
    ]
)

# --- Redefine and retrain the 4-class model with the fixed preprocessor ---
model_pipeline_fixed = Pipeline(steps=[
    ('preprocessor', preprocessor_fixed),
    ('classifier', RandomForestClassifier(random_state=42, n_estimators=175))
])

model_pipeline_fixed.fit(X_train, y_train)

# --- Predict and evaluate using the fixed pipeline ---
y_pred_rf = model_pipeline_fixed.predict(X_test)

print("=== 4-Class Model (Random Forest) ===")
print(classification_report(y_test, y_pred_rf))

cm_4class = confusion_matrix(y_test, y_pred_rf, labels=model_pipeline_fixed.classes_)
plt.figure(figsize=(7,5))
sns.heatmap(cm_4class, annot=True, fmt='d', cmap='Blues',
            xticklabels=model_pipeline_fixed.classes_, yticklabels=model_pipeline_fixed.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - 4-Class Model')
plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Re-create the binary train/test split for evaluation
# The df_model variable already contains the 'severity' column
X_binary = df_model[['device_name', 'event_description']]
y_binary = df_model['severity']

X_train_binary, X_test_binary, y_train_binary, y_test_binary = train_test_split(
    X_binary, y_binary, test_size=0.2, random_state=42, stratify=y_binary
)

# Use the correct X_test and y_test for binary classification
y_pred_binary = model_pipeline_binary.predict(X_test_binary)

print("=== Binary Model (Severe vs Non-Severe) ===")
print(classification_report(y_test_binary, y_pred_binary))

cm_binary = confusion_matrix(y_test_binary, y_pred_binary, labels=model_pipeline_binary.classes_)
plt.figure(figsize=(6,5))
sns.heatmap(cm_binary, annot=True, fmt='d', cmap='Greens',
            xticklabels=model_pipeline_binary.classes_, yticklabels=model_pipeline_binary.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Binary Model')
plt.show()

import joblib

joblib.dump(model_pipeline_binary, 'severity_model.pkl')
print("Model saved as severity_model.pkl")

from google.colab import files
files.download('severity_model.pkl')

import sklearn
print(sklearn.__version__)

# Upgrade karo 1.9.0 tak (tumhare local machine ke version se match karne ke liye)
!pip install --upgrade scikit-learn --quiet